#!/usr/bin/env tsx

/**
 * Regenerates the module G (task #19) model-classification data from the raw
 * source snapshot. Run this — never hand-edit data.ts or
 * data/model-classification.json's derived fields — whenever the raw
 * snapshot at the repo root is refreshed. Both output files are checked into
 * git (same pattern as generate-models.ts / models.generated.ts in this same
 * package): data.ts is what the build actually compiles (a plain TS literal
 * sidesteps this repo's root tsconfig `module: "Node16"`, which doesn't
 * support native `with { type: "json" }` imports — confirmed by probing
 * tsgo directly), and data/model-classification.json is the human-readable
 * canonical artifact. A drift test (model-classification.test.ts) fails if
 * the two ever fall out of sync.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { deriveModalityTags } from "../src/router/model-classification/modality.js";
import type { ModelClass } from "../src/router/model-classification/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(__dirname, "..");
const repoRoot = join(packageRoot, "..", "..");
const rawSourcePath = join(repoRoot, "llm_classification_2026_full.json");
const outDir = join(packageRoot, "src", "router", "model-classification");

interface RawBenchmarks {
	relative_grade: number | string;
	benchmarks: Record<string, number>;
}

interface RawPricing {
	input_per_1m: number | null;
	output_per_1m: number | null;
	notes?: string;
}

interface RawModel {
	name: string;
	provider: string;
	parameters?: string;
	weights_type?: string;
	hosted_by?: string;
	coding?: RawBenchmarks;
	reasoning?: RawBenchmarks;
	instruction_following?: Record<string, number>;
	pricing: RawPricing;
	rationale?: string;
}

interface RawSnapshot {
	metadata: {
		date: string;
		methodology: {
			coding_weight: string;
			reasoning_weight: string;
			instruction_following_weight: string;
			grading_method: string;
			demotion_rule: string;
			data_sources: string[];
			notation: string;
		};
	};
	classes: Record<string, { class_name: string; models: RawModel[]; description?: string }>;
}

function toBenchmarks(raw: RawBenchmarks | undefined) {
	if (!raw) return undefined;
	return { relativeGrade: raw.relative_grade, benchmarks: raw.benchmarks };
}

function toModel(raw: RawModel, modelClass: ModelClass, className: string) {
	return {
		name: raw.name,
		provider: raw.provider,
		parameters: raw.parameters,
		weightsType: raw.weights_type,
		hostedBy: raw.hosted_by,
		class: modelClass,
		className,
		coding: toBenchmarks(raw.coding),
		reasoning: toBenchmarks(raw.reasoning),
		instructionFollowing:
			raw.instruction_following && Object.keys(raw.instruction_following).length
				? raw.instruction_following
				: undefined,
		pricing: {
			inputPer1m: raw.pricing.input_per_1m,
			outputPer1m: raw.pricing.output_per_1m,
			notes: raw.pricing.notes || undefined,
		},
		rationale: raw.rationale,
		modality: deriveModalityTags(modelClass, raw.rationale),
	};
}

function main() {
	const rawSnapshot: RawSnapshot = JSON.parse(readFileSync(rawSourcePath, "utf8"));

	const models = [];
	for (const [modelClass, classEntry] of Object.entries(rawSnapshot.classes)) {
		for (const raw of classEntry.models) {
			models.push(toModel(raw, modelClass as ModelClass, classEntry.class_name));
		}
	}

	const integrated = {
		metadata: {
			date: rawSnapshot.metadata.date,
			methodology: {
				codingWeight: rawSnapshot.metadata.methodology.coding_weight,
				reasoningWeight: rawSnapshot.metadata.methodology.reasoning_weight,
				instructionFollowingWeight: rawSnapshot.metadata.methodology.instruction_following_weight,
				gradingMethod: rawSnapshot.metadata.methodology.grading_method,
				demotionRule: rawSnapshot.metadata.methodology.demotion_rule,
				dataSources: rawSnapshot.metadata.methodology.data_sources,
				notation: rawSnapshot.metadata.methodology.notation,
			},
		},
		models,
	};

	writeFileSync(join(outDir, "data", "model-classification.json"), `${JSON.stringify(integrated, null, "\t")}\n`);

	const dataTs =
		"/**\n" +
		" * Integrated, normalized classification data (task #19) -- flattened into a\n" +
		" * single models[] array (camelCase, per-model class/modality attached), not\n" +
		" * the raw nested-by-class shape of the source snapshot. GENERATED by\n" +
		" * scripts/generate-model-classification.ts from ./data/model-classification.json\n" +
		" * -- do not hand-edit; run that script instead after refreshing the raw\n" +
		" * source snapshot. (Embedded as a TS literal rather than a native JSON\n" +
		" * import: this repo targets module:Node16 in its root tsconfig, which\n" +
		" * doesn't support import attributes -- only nodenext/node18/node20/esnext do.)\n" +
		" */\n" +
		`export const INTEGRATED_CLASSIFICATION_DATA = ${JSON.stringify(integrated, null, "\t")} as const;\n`;
	writeFileSync(join(outDir, "data.ts"), dataTs);

	console.log(`Generated ${models.length} classified models across ${Object.keys(rawSnapshot.classes).length} classes.`);
}

main();
